version: "3"
services:
  celery:
    build: .
    command: "celery -A main.celery worker --loglevel=info"
    restart: always
    volumes:
      - .:/app
    networks:
      - api_consumer

  celery-beat:
    build: .
    command: "celery -A main.celery beat --loglevel=info"
    restart: always
    networks:
      - api_consumer
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    ports: 
      - 6379:6379
    networks:
      - api_consumer

networks:
  api_consumer:

